import type { RoadDefect } from '@/lib/types'

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString()
const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString()

// Defects are DEDUPLICATED by location: when multiple buses report the same
// spot, it is one defect record whose observationCount and reportingBuses grow.
export const ROAD_DEFECTS: RoadDefect[] = [
  {
    id: 'RD-001',
    defectType: 'Pothole',
    location: 'Madhapur Road',
    area: 'Madhapur',
    coordinates: { lat: 17.4483, lng: 78.3915 },
    observationCount: 9,
    reportingBuses: ['BUS-101', 'BUS-217', 'BUS-404', 'BUS-518'],
    confidence: 94,
    severity: 'Critical',
    status: 'In Progress',
    firstDetected: hoursAgo(52),
    lastDetected: minutesAgo(6),
  },
  {
    id: 'RD-002',
    defectType: 'Broken Manhole',
    location: 'Gachibowli Flyover',
    area: 'Gachibowli',
    coordinates: { lat: 17.4401, lng: 78.3489 },
    observationCount: 6,
    reportingBuses: ['BUS-205', 'BUS-101', 'BUS-404'],
    confidence: 90,
    severity: 'Critical',
    status: 'Verified',
    firstDetected: hoursAgo(38),
    lastDetected: minutesAgo(19),
  },
  {
    id: 'RD-003',
    defectType: 'Crack',
    location: 'KPHB Main Road',
    area: 'Kukatpally',
    coordinates: { lat: 17.4948, lng: 78.3996 },
    observationCount: 7,
    reportingBuses: ['BUS-217', 'BUS-518'],
    confidence: 85,
    severity: 'High',
    status: 'New',
    firstDetected: hoursAgo(30),
    lastDetected: minutesAgo(12),
  },
  {
    id: 'RD-004',
    defectType: 'Pothole',
    location: 'Ameerpet Flyover',
    area: 'Ameerpet',
    coordinates: { lat: 17.4374, lng: 78.4487 },
    observationCount: 5,
    reportingBuses: ['BUS-312', 'BUS-101'],
    confidence: 81,
    severity: 'High',
    status: 'Verified',
    firstDetected: hoursAgo(26),
    lastDetected: minutesAgo(41),
  },
  {
    id: 'RD-005',
    defectType: 'Debris',
    location: 'Uppal Ring Road',
    area: 'Uppal',
    coordinates: { lat: 17.4058, lng: 78.5591 },
    observationCount: 4,
    reportingBuses: ['BUS-312'],
    confidence: 76,
    severity: 'Medium',
    status: 'New',
    firstDetected: hoursAgo(18),
    lastDetected: hoursAgo(2),
  },
  {
    id: 'RD-006',
    defectType: 'Faded Marking',
    location: 'Kondapur Junction',
    area: 'Kondapur',
    coordinates: { lat: 17.4615, lng: 78.3645 },
    observationCount: 3,
    reportingBuses: ['BUS-518', 'BUS-217'],
    confidence: 72,
    severity: 'Low',
    status: 'Resolved',
    firstDetected: hoursAgo(60),
    lastDetected: hoursAgo(20),
  },
  {
    id: 'RD-007',
    defectType: 'Pothole',
    location: 'Miyapur X Roads',
    area: 'Miyapur',
    coordinates: { lat: 17.4968, lng: 78.3608 },
    observationCount: 8,
    reportingBuses: ['BUS-518', 'BUS-217', 'BUS-101'],
    confidence: 88,
    severity: 'High',
    status: 'In Progress',
    firstDetected: hoursAgo(44),
    lastDetected: minutesAgo(38),
  },
  {
    id: 'RD-008',
    defectType: 'Crack',
    location: 'Banjara Hills Rd No. 12',
    area: 'Banjara Hills',
    coordinates: { lat: 17.4156, lng: 78.4347 },
    observationCount: 2,
    reportingBuses: ['BUS-404'],
    confidence: 69,
    severity: 'Low',
    status: 'New',
    firstDetected: hoursAgo(9),
    lastDetected: hoursAgo(1),
  },
]
